# Generated by Django 2.2.4 on 2019-09-08 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('nom_ar', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorieVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('nom_ar', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='images/locations/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageVentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='images/ventes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lieux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('nom_ar', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteTel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('tel', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('isRegistred', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VenteRecheche1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('prix', models.PositiveIntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.CategorieVente')),
                ('lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Lieux')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VenteRecheche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('prix_min', models.PositiveIntegerField()),
                ('prix_max', models.PositiveIntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.CategorieVente')),
                ('lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Lieux')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationRecheche1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('prix', models.PositiveIntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.CategorieLocation')),
                ('lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Lieux')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationRecheche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('prix_min', models.PositiveIntegerField()),
                ('prix_max', models.PositiveIntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.CategorieLocation')),
                ('lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Lieux')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommonVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('prix', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('isPublier', models.BooleanField(default=False)),
                ('isPublicite', models.BooleanField(default=False)),
                ('isVendue', models.BooleanField(default=False)),
                ('isRejected', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.CategorieVente')),
                ('images', models.ManyToManyField(default=None, to='baseApp.ImageVentes')),
                ('lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Lieux')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommonLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('prix', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
                ('isPublier', models.BooleanField(default=False)),
                ('isPublicite', models.BooleanField(default=False)),
                ('isVendue', models.BooleanField(default=False)),
                ('isRejected', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.CategorieLocation')),
                ('images', models.ManyToManyField(default=None, to='baseApp.ImageLocations')),
                ('lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Lieux')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_last_change', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
